name: Notify

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo "All workflows passed!"